### Criar um investidor
POST http://localhost:3000/investors
Content-Type: application/json

{
  "email": "teste@teste.com",
  "name": "John Doe",
  "cpf": "12345678901",
  "password": "#senhaSegura123",
  "dateOfBirth": "1995-05-20"
}

### Buscar todos os investidores
GET http://localhost:3000/investors

### Buscar investidor por ID
GET http://localhost:3000/investors/{{id}}

### Atualizar investidor
PUT http://localhost:3000/investors/{{id}}
Content-Type: application/json

{
  "name": "Novo Nome",
  "password": "novaSenha123"
}

### Remover investidor
DELETE http://localhost:3000/investors/{{id}}
